apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama-system
spec:
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: hermes-model
  ports:
    - port: 11434
      targetPort: 11434
