apiVersion: ark.mckinsey.com/v1alpha1
kind: Query
metadata:
  name: diagnose-coredns
spec:
  input: "Why is the coredns pod in kube-system namespace not ready? Please diagnose."
  target:
      name: pod-doctor
      type: agent
